"""Builds docs/CODE_REFERENCE.md from the source (functions, classes, routes, first docstring line).
Run after changing code:  python tools/gen_code_map.py"""
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FILES = ["main.py", "config.py", "constants.py", "util.py", "db.py", "agent.py", "jobs.py", "oauth.py",
         "mcp_app.py", "mcp_server.py", "evals/checks.py", "evals/run_evals.py", "tools/gen_code_map.py"]


def route(dec):
    if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute) and dec.func.attr in ("get", "post", "put", "delete") \
            and dec.args and isinstance(dec.args[0], ast.Constant):
        return f"{dec.func.attr.upper()} {dec.args[0].value}"
    if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute) and dec.func.attr == "tool":
        return "MCP tool"
    return None


def first_line(node):
    doc = ast.get_docstring(node)
    return doc.strip().splitlines()[0] if doc else ""


out = ["# Code reference (auto-generated)\n",
       "Generated by `python tools/gen_code_map.py`. Do not edit by hand; edit docstrings in the code instead.",
       "Read `CODE_GUIDE.md` first for the big picture.\n"]
for name in FILES:
    tree = ast.parse((ROOT / name).read_text())
    out.append(f"## `{name}`\n")
    mod = first_line(tree)
    if mod:
        out.append(f"{mod}\n")
    rows = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            routes = ", ".join(filter(None, (route(d) for d in node.decorator_list)))
            args = ", ".join(a.arg for a in node.args.args)
            kind = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
            rows.append((f"`{kind} {node.name}({args})`", routes or "", first_line(node), node.lineno))
        elif isinstance(node, ast.ClassDef):
            rows.append((f"`class {node.name}`", "", first_line(node), node.lineno))
    if rows:
        out += ["| Function / class | Route or role | What it does | Line |", "|---|---|---|---|"]
        out += [f"| {a} | {b} | {c.replace('|', '/')} | {d} |" for a, b, c, d in rows]
        out.append("")
(ROOT / "docs" / "CODE_REFERENCE.md").write_text("\n".join(out) + "\n")
print("wrote docs/CODE_REFERENCE.md")
